workflows:
  ios_ipa:
    name: iOS IPA (Flutter)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build iOS IPA
        script: |
          flutter build ipa \
            --release \
            --export-method development

    artifacts:
      - build/ios/ipa/*.ipa
