workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      groups:
        - keystore
    scripts:
      - name: Install Flutter
        script: |
          flutter --version
          flutter pub get
      - name: Build Android
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
