workflows:
  ios-simulator:
    name: iOS Simulator Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ios --simulator --debug
    artifacts:
      - build/ios/iphonesimulator/*.app